sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: 'wager-service@%app.version%'
        traces_sample_rate: 1.0  # 100% sampling for POC
        profiles_sample_rate: 1.0  # 100% profiling for POC
        send_default_pii: true  # Include user context
        attach_stacktrace: true
        capture_silenced_errors: true
        
        # Integrations are now auto-configured in Sentry SDK 4+
        # integrations: []
            
        # Business transaction names handled in subscriber