controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Health check route
health:
    path: /health
    controller: App\Controller\HealthController::check
    methods: GET